# Exported from Render on 2026-01-06T15:03:51Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: chromium
      runtime: image
      image:
        url: ghcr.io/browserless/chromium:latest
      plan: free
      envVars:
      - key: CONNECTION_TIMEOUT
        sync: false
      - key: CONCURRENT
        sync: false
      - key: TIMEOUT
        sync: false
      region: oregon
      autoDeployTrigger: commit
